### ISSUE TITLE
another git issue to look at.

### ISSUE THREAD

**Issue by altmattr** [mqjasper/mq-pi-gen#4]
something funny with git permissions or ownership on fresh image

`````
pi@mqpi:~/stem_club $ git status
fatal: detected dubious ownership in repository at '/home/pi/stem_club'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/pi/stem_club
`````

**Comment by mqjasper** [comment]
The build process should now set all files in the home directory to the correct ownership. Will have to double check next time I go through the motions
